name: "Test"

on:
  pull_request:
    branches: ["master"]

permissions:
  checks: write

jobs:
  test:
    name: "Test"
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: zulu
          cache: sbt

      - name: Run Tests
        run: sbt +test

      - name: Test Report
        uses: mikepenz/action-junit-report@v3
        if: always()
        with:
          check_name: Test Report
          report_paths: target/test-reports/scala-*/TEST-*.xml
